import express from "express";
import { listBooksController } from "./controller.list-books.js";
import { healthController } from "./controller.health.js";
import { getBookController } from "./controller.get-book.js";
import { generateBookController } from "./controller.generate-book.js";
import { clientController } from "./controller.client.js";
import { updateBookController } from "./controller.update-book.js";
import { updateAppController } from "./controller.update-app.js";
import { getAppConfigController } from "./controller.get-app-config.js";
import { registerUploadReference } from "./controller.upload-reference.js";
import { updateChapterController } from "./controller.update-chapter.js";
import { updatePartController } from "./controller.update-part.js";
import { generatePartController } from "./controller.generate-part.js";
import { registerDownloadBook } from "./controller.download-book.js";
import { generateChapterOutlineController } from "./controller.generate-chapter-outline.js";
import { deleteBookController } from "./controller.delete-book.js";
import { createBookController } from "./controller.create-book.js";
import { generatePartAudioController } from "./controller.generate-part-audio.js";
import { registerGetChapterAudio } from "./controller.get-part-audio.js";
import { registerDownloadBookAudio } from "./controller.download-book-audio.js";
import { generatePartOutlineController } from "./controller.generate-part-outline.js";
import { appPingModelController } from "./controller.app-ping-model.js";

const router = express.Router();

healthController.register(router);
listBooksController.register(router);
getBookController.register(router);
generateBookController.register(router);
clientController.register(router);
updateBookController.register(router);
updateAppController.register(router);
getAppConfigController.register(router);
updateChapterController.register(router);
updatePartController.register(router);
generatePartController.register(router);
generateChapterOutlineController.register(router);
deleteBookController.register(router);
createBookController.register(router);
generatePartAudioController.register(router);
generatePartOutlineController.register(router);
registerUploadReference(router);
registerDownloadBook(router);
registerDownloadBookAudio(router);
registerGetChapterAudio(router);
appPingModelController.register(router);

export { router };
